#!/usr/bin/env bash

cd $HOME
ln -s $HOME/dotfiles/zshrc .zshrc
ln -s $HOME/dotfiles/tmux.conf .tmux.conf
ln -s $HOME/dotfiles/ignore .ignore
ln -s $HOME/dotfiles/ignore .fdignore
ln -s $HOME/dotfiles/gitconfig .gitconfig
ln -s $HOME/dotfiles/rubocop.yml .rubocop.yml
ln -s $HOME/dotfiles/psqlrc .psqlrc
mkdir .lein
ln -s $HOME/dotfiles/lein/profiles.clj .lein/profiles.clj
mkdir .boot
ln -s $HOME/dotfiles/boot.properties .boot/boot.properties
mkdir .clojure
ln -s $HOME/dotfiles/clojure/deps.edn .clojure/deps.edn
mkdir .config
mkdir .config/nvim
ln -s $HOME/dotfiles/nvim/init.vim .config/nvim/init.vim
mkdir .config/nvim/Ultisnips
mkdir .config/nvim/ftdetect
ln -s $HOME/dotfiles/nvim/ftdetect/* .config/nvim/ftdetect
mkdir .config/nvim/ftplugin
ln -s $HOME/dotfiles/nvim/ftplugin/* .config/nvim/ftplugin
ln -s $HOME/dotfiles/nvim/Ultisnips/javascript.snippets .config/nvim/Ultisnips
ln -s $HOME/dotfiles/nvim/Ultisnips/javascript.snippets .config/nvim/Ultisnips/typescript.snippets
ln -s $HOME/dotfiles/nvim/coc-settings.json .config/nvim/coc-settings.json
mkdir .ghc
ln -s $HOME/dotfiles/ghci.conf .ghc/ghci.conf
mkdir .ctags.d
ln -s $HOME/dotfiles/ctags .ctags.d/defaults.ctags
mkdir .vim
mkdir .vim/tmp
mkdir .vim/undo
mkdir .vim-plug-snapshots
