#!/usr/bin/env bash

source ./build-symlinks

cd $HOME
mkdir Library/KeyBindings
ln -s $HOME/dotfiles/DefaultKeyBinding.dict Library/KeyBindings/DefaultKeyBinding.dict
mkdir .config/alacritty
ln -s $HOME/dotfiles/alacritty.yml .config/alacritty/alacritty.yml
ln -s $HOME/dotfiles/chunkwmrc .chunkwmrc
ln -s $HOME/dotfiles/skhdrc .skhdrc
