#!/usr/bin/env bash

chunkc core::plugin_dir /usr/local/opt/chunkwm/share/chunkwm/plugins
chunkc core::hotload 0

chunkc set global_desktop_mode           monocle
chunkc set global_desktop_offset_top     0
chunkc set global_desktop_offset_bottom  0
chunkc set global_desktop_offset_left    0
chunkc set global_desktop_offset_right   0
chunkc set global_desktop_offset_gap     0

# NOTE: syntax for desktop-specific settings
#
# chunkc set 2_desktop_mode                bsp
# chunkc set 5_desktop_mode                float
# chunkc set 3_desktop_offset_top          190

chunkc set bsp_spawn_left                0
chunkc set bsp_optimal_ratio             1.618
chunkc set bsp_split_mode                optimal
chunkc set bsp_split_ratio               0.5

chunkc set monitor_focus_cycle           1
chunkc set window_focus_cycle            monitor

chunkc set mouse_follows_focus           0
chunkc set window_float_next             0
chunkc set window_region_locked          1

chunkc core::load tiling.so
# chunkc core::load ffm.so

# NOTE: sample rules for the tiling plugin
chunkc tiling::rule --owner 1Password --state float
chunkc tiling::rule --owner Finder --state float
chunkc tiling::rule --owner FaceTime --state float
chunkc tiling::rule --owner Calculette --state float
chunkc tiling::rule --owner \"App Store\" --state float
chunkc tiling::rule --owner Emacs --except "^$" --state tile
