#!/usr/bin/env bash

cd $HOME
touch .hushlogin

echo "Getting command line tools"
xcode-select --install

echo "Setting up homebrew and packages"
/usr/bin/ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"

brew tap homebrew/cask-versions

brew cask install \
  basictex \
  google-chrome \
  kitty \
  java8 \
  ngrok \
  typora

brew install \
  awk \
  boot-clj \
  clojure \
  curl \
  fd \
  fzf \
  getantibody/tap/antibody \
  git \
  gnu-sed --with-default-names \
  heroku/brew/heroku \
  hub \
  jq \
  leiningen \
  neovim \
  postgresql \
  python \
  python@2 \
  pipenv \
  ruby \
  reattach-to-user-namespace \
  ripgrep \
  rlwrap \
  stack \
  the_silver_searcher \
  tmux \
  tree \
  watchman \
  z \
  zsh \

brew tap universal-ctags/universal-ctags
brew install --HEAD universal-ctags/universal-ctags/universal-ctags

brew services start postgres
psql -d postgres -c "create database adc".

echo "Performing homebrew post-installations"
$(brew --prefix)/opt/fzf/install

echo "Setting up SSH"
ssh-keygen -t rsa -b 4096 -C "contact@alexchalk.net"
echo "Host *\n  AddKeysToAgent yes\n  UseKeychain yes\n  IdentityFile ~/.ssh/id_rsa" >> $HOME/.ssh/config
eval "$(ssh-agent -s)"
ssh-add -K $HOME/.ssh/id_rsa

echo "Node"
curl -L https://git.io/n-install | bash

echo "Rust"
curl https://sh.rustup.rs -sSf | sh

echo "Vim Plug Setup"
curl -fLo ~/.local/share/nvim/site/autoload/plug.vim --create-dirs \
  https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim

echo "Clone Personal Notes"
git clone git@gitlab.com:adc17/personal-wiki.git $HOME/vimwiki
