#!/usr/bin/env bash

cd $HOME
touch .hushlogin

echo "Getting command line tools"
xcode-select --install

echo "Setting up SSH"
ssh-keygen -t ed25519 -C "contact@alexchalk.net"
eval "$(ssh-agent -s)"
ssh-add $HOME/.ssh/id_ed25519
if [[ "$OSTYPE" == darwin* ]]; then
  echo "Host *\n  AddKeysToAgent yes\n  UseKeychain yes\n  IdentityFile ~/.ssh/id_ed25519" >> $HOME/.ssh/config
fi

# Fonts
echo "Getting personal fonts"
git clone git@github.com:AlexChalk/fonts-private.git $HOME/Library/Fonts

echo "Setting up nix"
sh <(curl -L https://nixos.org/nix/install) --darwin-use-unencrypted-nix-store-volume --no-daemon

echo "Setting up homebrew"
/bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"

brew tap homebrew/cask-versions

brew cask install \
  basictex \
  brave-browser \
  keepingyouawake \
  kitty \
  adoptopenjdk8 \
  ngrok \
  postgres \
  typora

brew install \
  awk \
  boot-clj \
  clojure \
  curl \
  fd \
  fzf \
  git \
  gnu-sed --with-default-names \
  heroku/brew/heroku \
  hub \
  jq \
  leiningen \
  neovim \
  python \
  python@2 \
  pipenv \
  ruby \
  ripgrep \
  rlwrap \
  stack \
  the_silver_searcher \
  tmux \
  tree \
  watchman \
  zsh \

brew tap universal-ctags/universal-ctags
brew install --HEAD universal-ctags/universal-ctags/universal-ctags

brew services start postgres
psql -d postgres -c "create database adc".

echo "Performing homebrew post-installations"
$(brew --prefix)/opt/fzf/install

echo "Node"
curl -L https://git.io/n-install | bash

echo "Rust"
curl https://sh.rustup.rs -sSf | sh

echo "zplugin Setup"
sh -c "$(curl -fsSL https://raw.githubusercontent.com/zdharma/zplugin/master/doc/install.sh)"

echo "Vim Plug Setup"
curl -fLo ~/.local/share/nvim/site/autoload/plug.vim --create-dirs \
  https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim

echo "Clone Personal Notes"
git clone git@github.com:AlexChalk/personal-wiki.git $HOME/vimwiki

echo "Haskell tooling"
git clone https://github.com/haskell/haskell-ide-engine --recurse-submodules
