#!/usr/bin/env bash

cd $HOME
touch .hushlogin

echo "Getting command line tools"
xcode-select --install

echo "Setting up SSH"
# https://docs.github.com/en/authentication/connecting-to-github-with-ssh/generating-a-new-ssh-key-and-adding-it-to-the-ssh-agent
ssh-keygen -t ed25519 -C "contact@alexchalk.net"
eval "$(ssh-agent -s)"
ssh-add $HOME/.ssh/id_ed25519
if [[ "$OSTYPE" == darwin* ]]; then
  echo "Host *\n  AddKeysToAgent yes\n  UseKeychain yes\n  IdentityFile ~/.ssh/id_ed25519" >> $HOME/.ssh/config
fi

# Fonts
echo "Getting personal fonts"
git clone git@github.com:AlexChalk/fonts-private.git $HOME/Library/Fonts

echo "Setting up nix"
sh <(curl -L https://releases.nixos.org/nix/nix-2.3.16/install) --darwin-use-unencrypted-nix-store-volume --no-daemon

nix-channel --add https://nixos.org/channels/nixpkgs-21.11-darwin nixpkgs-stable
nix-channel --add https://nixos.org/channels/nixpkgs-unstable nixpkgs   
nix-channel --update

diskutil list | grep -i nix
diskutil apfs encryptvolume {{your-device-name}} -user disk
# (store password, before entering)
diskutil apfs list # reboot if encryption is complete

echo "Setting up homebrew"
/bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"

brew install --cask \
  1password \
  adguard \
  discord \
  docker \
  firefox \
  flux \
  insomnia \
  keepingyouawake \
  kitty \
  maestral \
  ngrok \
  obsidian \
  postgres-unofficial \
  signal \
  homebrew/cask-drivers/uhk-agent \
  zoom

sudo mkdir -p /etc/paths.d && echo /Applications/Postgres.app/Contents/Versions/latest/bin | sudo tee /etc/paths.d/postgresapp

echo "Misc. non-nix"
brew install \
  circleci \
  openapi-generator \
  openjdk

echo "Graalvm (nix broken on mac)"
brew install \
  clojure-lsp/brew/clojure-lsp-native \
  borkdude/brew/babashka

echo "Window managers"
brew install \
  koekeishiya/formulae/yabai \
  koekeishiya/formulae/skhd

brew services start yabai
brew services start skhd

echo "zinit Setup"
sh -c "$(curl -fsSL https://git.io/zinit-install)"

echo "Vim Plug Setup"
curl -fLo ~/.local/share/nvim/site/autoload/plug.vim --create-dirs \
  https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim

echo "Clone Personal Notes"
git clone git@github.com:AlexChalk/personal-wiki.git $HOME/vimwiki

echo "Haskell tooling"
git clone https://github.com/haskell/haskell-ide-engine --recurse-submodules
