#!/usr/bin/env bash

yarn global add neovim \
  elm \
  elm-format \
  elm-oracle \
  elm-test \
  typescript \
  typescript-language-server \
  purescript \
  purescript-psa \
  pulp \
  bower \
  shadow-cljs
