#!/usr/bin/env bash

pip2 install \
  pynvim
pip3 install \
  pynvim \
  python-language-server \
  jedi \
  sqlparse

# If neovim has issues finding the package
# pip2 install --upgrade --force-reinstall neovim
