#!/usr/bin/env bash

# ====== Variables =============================

gaps_top="0"
gaps_bottom="0"
gaps_left="0"
gaps_right="0"
gaps_inner="0"

# ====== Tiling settings =======================

yabai -m config layout                      stack

yabai -m config top_padding                 "${gaps_top}"
yabai -m config bottom_padding              "${gaps_bottom}"
yabai -m config left_padding                "${gaps_left}"
yabai -m config right_padding               "${gaps_right}"
yabai -m config window_gap                  "${gaps_inner}"

yabai -m config mouse_follows_focus         off
yabai -m config focus_follows_mouse         off

yabai -m config mouse_modifier              fn
yabai -m config mouse_action1               move
yabai -m config mouse_action2               resize
yabai -m config mouse_drop_action           swap

yabai -m config window_placement            second_child
yabai -m config window_topmost              off
yabai -m config window_opacity              off
yabai -m config window_shadow               off
yabai -m config insert_feedback_color       0xffd75f5f

yabai -m config window_opacity_duration     0.0
yabai -m config active_window_opacity       1.0
yabai -m config normal_window_opacity       0.9
yabai -m config split_ratio                 0.5
yabai -m config auto_balance                off

# ====== Rules =======================

yabai -m rule --add label="1Password" app="^1Password$" manage=off
yabai -m rule --add label="Finder" app="^Finder$" manage=off
yabai -m rule --add label="System Preferences" app="^System Preferences$" manage=off
yabai -m rule --add label="FaceTime" app="^FaceTime$" manage=off
yabai -m rule --add label="Calculette" app="^Calculette$" manage=off
yabai -m rule --add label="App Store" app="^App Store$" manage=off
