;;;;adc17's emacs.d/init.el file (I started doing this properly on 12/29/2016). 

;;;Autogenerated stuff
(custom-set-variables
  ;; custom-set-variables was added by Custom.
  ;; If you edit it by hand, you could mess it up, so be careful.
  ;; Your init file should contain only one such instance.
  ;; If there is more than one, they won't work right.
  '(custom-safe-themes
     (quote
       ("628278136f88aa1a151bb2d6c8a86bf2b7631fbea5f0f76cba2a0079cd910f7d" default))))

;;;Specifies how emacs window will initially render.
(setq initial-frame-alist '((top . 0) (left . 97) (width . 140) (height . 50)))
(setq inhibit-splash-screen t)
(tool-bar-mode -1)
(scroll-bar-mode -1)
(menu-bar-mode 0)

;;;Adds package archives and disables package loading until init file has been executed.

(require 'package)

(setq package-archives
      '(("gnu elpa"     . "http://elpa.gnu.org/packages/")
        ("org"          . "http://orgmode.org/elpa/")
        ("melpa"        . "https://melpa.org/packages/")))

(setq package-enable-at-startup nil)
(package-initialize)

;;; Bootloader for use-package.
(unless (package-installed-p 'use-package)
  (package-refresh-contents)
  (package-install 'use-package))

;; Buffer navigaton
(setq ns-pop-up-frames nil)

;; Specify window in which certain buffers will open.
(customize-set-variable
 'display-buffer-alist
 '(("\\*magit: .*"      display-buffer-same-window)))

;; Display
(set-default-font "Menlo 14")
(setq scroll-margin 5)
(setq scroll-step 1)

;;; Configure theme
(use-package color-theme-sanityinc-tomorrow
             :ensure t
             :config)
(load-theme 'sanityinc-tomorrow-eighties)

(use-package magit
  :ensure t
  :bind ("C-x g" . magit-status))
  ; :bind ("C-x k" . with-editor-cancel))

(magit-status)
