-- -----------------------------------------------------
-- -- Clojure
-- -----------------------------------------------------
-- if vim.g.parinfer_mode == "smart" then
--   vim.g.parinfer_mode = "paren"
-- end
